SIM:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"\"

SIMGRAY:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGrayDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"use_gray=true\"

SIMROWS:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneRowsDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"divide_rows=true\"

SIMROWSGRAY:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneRowsGrayDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"divide_rows=true use_gray=true\"

SIMGLYNN:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGlynnDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"glynn=true\"

SIMGLYNNROWS:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGlynnRowsDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"divide_rows=true glynn=true\"

SIMGLYNNGRAY:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGlynnGrayDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"glynn=true use_gray=true\"

SIMGLYNNROWSGRAY:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGlynnRowsGrayDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"divide_rows=true glynn=true use_gray=true\"

SIMDUAL:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneDualDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"dual=true\"

SIMGRAYDUAL:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGrayDualDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"use_gray=true dual=true\"

SIMROWSDUAL:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneRowsDualDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"divide_rows=true dual=true\"

SIMROWSGRAYDUAL:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneRowsGrayDualDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"divide_rows=true use_gray=true dual=true\"

SIMGLYNNDUAL:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGlynnDualDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"glynn=true dual=true\"

SIMGLYNNROWSDUAL:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGlynnRowsDualDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"divide_rows=true glynn=true dual=true\"

SIMGLYNNGRAYDUAL:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGlynnGrayDualDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"glynn=true use_gray=true dual=true\"

SIMGLYNNROWSGRAYDUAL:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGlynnRowsGrayDualDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"divide_rows=true glynn=true use_gray=true dual=true\"
 
DFE:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE -Dmaxfile-name=PermanentZOneDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/bitstream -Dengine-params=\"\"

.PHONY:

