SIM:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneSIM -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"\"

SIMGRAY:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGraySIM -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"use_gray=true\"

SIMROWS:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneRowsSIM -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"divide_rows=true\"

SIMROWSGRAY:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneRowsGraySIM -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"divide_rows=true use_gray=true\"

SIMGLYNN:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGlynnSIM -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"glynn=true\"

SIMGLYNNROWS:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGlynnRowsSIM -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"divide_rows=true glynn=true\"

SIMGLYNNGRAY:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGlynnGraySIM -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"glynn=true use_gray=true\"

SIMGLYNNROWSGRAY:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGlynnRowsGraySIM -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"divide_rows=true glynn=true use_gray=true\"

SIMDUAL:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneDualSIM -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"dual=true\"

SIMGRAYDUAL:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGrayDualSIM -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"use_gray=true dual=true\"

SIMROWSDUAL:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneRowsDualSIM -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"divide_rows=true dual=true\"

SIMROWSGRAYDUAL:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneRowsGrayDualSIM -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"divide_rows=true use_gray=true dual=true\"

SIMGLYNNDUAL:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGlynnDualSIM -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"glynn=true dual=true\"

SIMGLYNNROWSDUAL:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGlynnRowsDualSIM -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"divide_rows=true glynn=true dual=true\"

SIMGLYNNGRAYDUAL:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGlynnGrayDualSIM -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"glynn=true use_gray=true dual=true\"

SIMGLYNNROWSGRAYDUAL:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGlynnRowsGrayDualSIM -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"divide_rows=true glynn=true use_gray=true dual=true\"
 
DFEROWSGRAY:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE -Dmaxfile-name=PermanentZOneRowsGrayDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/bitstream -Dengine-params=\"divide_rows=true use_gray=true\"

DFEROWSGRAYDUAL:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE -Dmaxfile-name=PermanentZOneRowsGrayDualDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/bitstream -Dengine-params=\"divide_rows=true use_gray=true dual=true\"

DFEGLYNNROWSGRAY:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE -Dmaxfile-name=PermanentZOneGlynnRowsGrayDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/bitstream -Dengine-params=\"divide_rows=true glynn=true use_gray=true\"

DFEGLYNNROWSGRAYDUAL:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE -Dmaxfile-name=PermanentZOneGlynnRowsGrayDualDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/bitstream -Dengine-params=\"divide_rows=true glynn=true use_gray=true dual=true\"

.PHONY:

