SIM:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"\"

SIMGRAY:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneGrayDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"use_gray=true\"

SIMROWS:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneRowsDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"divide_rows=true\"

SIMROWSGRAY:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE_SIM -Dmaxfile-name=PermanentZOneRowsGrayDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/simulation -Dengine-params=\"divide_rows=true use_gray=true\"

DFE:
	ant build -Dmanager=permanentzone.PermanentZOneDFEManagerAlveoU250 -Dtarget=DFE -Dmaxfile-name=PermanentZOneDFE -Dresult-dir=/home/morse/workspace/PermanentZOneDFE/builds/bitstream -Dengine-params=\"\"

.PHONY:

